theme: jekyll-theme-cayman
title: David Bauer
description: What you should expect from me.
![](https://github.com/Jussy23/http-jussy23.github.io-/blob/master/customer-service-attentivennes.png?raw=true)
